blank_issues_enabled: false
contact_links:
  - name: Feature Requests
    url: https://github.com/RickRyan26/skin.rixflix/issues/new
    about: Request a new feature or changes to an existing feature
  - name: Q&A Discussions
    url: https://github.com/RickRyan26/skin.rixflix/issues/new
    about: Ask for help from the community here
  - name: Show and Tell
    url: https://github.com/RickRyan26/skin.rixflix/issues/new
    about: Show off your skin setup here
